In [1]:
#install the libraries
!pip install requests pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: requests in c:\users\priyanka\appdata\roaming\python\python311\site-packages (2.31.0)

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pandas in c:\users\priyanka\appdata\roaming\python\python311\site-packages (2.1.4)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\priyanka\appdata\roaming\python\python311\site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\priyanka\appdata\roaming\python\python311\site-packages (from requests) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\priyanka\appdata\roaming\python\python311\site-packages (from requests) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\priyanka\appdata\roaming\python\python311\site-packages (from requests) (2023.11.17)
Requirement already satisfied: numpy<2,>=1.23.2 in c:\users\priyanka\appdata\roaming\python\python311\site-packages (from pandas) (1.26.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\priyanka\appdata\roaming\python\python311\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\priyanka\appdata\roaming\python\python311\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\priyanka\appdata\roaming\python\python311\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\priyanka\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [3]:
import requests
import pandas as pd

In [5]:
import requests

url = "https://fakestoreapi.com/products"

try:
    response = requests.get(url, timeout=10)
    response.raise_for_status()
    data = response.json()
    print(data[:2])
except requests.exceptions.RequestException as e:
    print("Error:", e)

[{'id': 1, 'title': 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops', 'price': 109.95, 'description': 'Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday', 'category': "men's clothing", 'image': 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_t.png', 'rating': {'rate': 3.9, 'count': 120}}, {'id': 2, 'title': 'Mens Casual Premium Slim Fit T-Shirts ', 'price': 22.3, 'description': 'Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing. And Solid stitched shirts with round neck made for durability and a great fit for casual fashion wear and diehard baseball fans. The Henley style round neckline includes a three-button placket.', 'category': "men's clothing", 'image': 'https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_t.png', 'rating': {'rate': 4.1, 'count': 259}}]

In [6]:
# Convert JSON to DataFrame
df = pd.json_normalize(data)

df.head()

,id,title,price,description,category,image,rating.rate,rating.count
0,1,"Fjallraven - Foldsack No. 1 Backpack, Fits 15 ...",109.95,Your perfect pack for everyday use and walks i...,men's clothing,https://fakestoreapi.com/img/81fPKd-2AYL._AC_S...,3.9,120
1,2,Mens Casual Premium Slim Fit T-Shirts,22.30,"Slim-fitting style, contrast raglan long sleev...",men's clothing,https://fakestoreapi.com/img/71-3HjGNDUL._AC_S...,4.1,259
2,3,Mens Cotton Jacket,55.99,great outerwear jackets for Spring/Autumn/Wint...,men's clothing,https://fakestoreapi.com/img/71li-ujtlUL._AC_U...,4.7,500
3,4,Mens Casual Slim Fit,15.99,The color could be slightly different between ...,men's clothing,https://fakestoreapi.com/img/71YXzeOuslL._AC_U...,2.1,430
4,5,John Hardy Women's Legends Naga Gold & Silver ...,695.00,"From our Legends Collection, the Naga was insp...",jewelery,https://fakestoreapi.com/img/71pWzhdJNwL._AC_U...,4.6,400

In [7]:
#rename column 
df = df[['id', 'title', 'price', 'category', 'rating.rate', 'rating.count']]

df.columns = ['ProductID', 'ProductName', 'Price', 'Category', 'Rating', 'RatingCount']

df.head()

,ProductID,ProductName,Price,Category,Rating,RatingCount
0,1,"Fjallraven - Foldsack No. 1 Backpack, Fits 15 ...",109.95,men's clothing,3.9,120
1,2,Mens Casual Premium Slim Fit T-Shirts,22.30,men's clothing,4.1,259
2,3,Mens Cotton Jacket,55.99,men's clothing,4.7,500
3,4,Mens Casual Slim Fit,15.99,men's clothing,2.1,430
4,5,John Hardy Women's Legends Naga Gold & Silver ...,695.00,jewelery,4.6,400

In [8]:
#export to csv
df.to_csv(r"E:\E-Commerce Sales Analysis\products.csv", index=False)

In [9]:
#i will do data cleaning in sql server